/*
  # Add Mass Update Feature

  1. Modified Tables
    - `quote_lanes`
      - `lane_status` (text) - Status of the lane: New, Active, Expired, Inactive
      - `lane_origin` (text) - How the lane was created: Customer Request, Mass Update, Renewal
    - `accounts`
      - `customer_email` (text) - Customer email for mass update notifications
    - `quotes`
      - `is_mass_update` (boolean) - Whether this quote was generated by mass update
      - `mass_update_log_id` (uuid) - Reference to the mass update log entry

  2. New Tables
    - `mass_update_log`
      - `id` (uuid, primary key)
      - `run_at` (timestamptz) - When the mass update was executed
      - `run_by` (text) - Who initiated the mass update
      - `filter_criteria` (jsonb) - Filter criteria used
      - `fields_modified` (jsonb) - Which fields were modified and how
      - `total_lanes_selected` (integer) - Number of lanes selected
      - `total_quotes_created` (integer) - Number of quotes created
      - `total_emails_sent` (integer) - Number of emails sent
      - `total_emails_flagged` (integer) - Number of emails flagged
      - `results` (jsonb) - Per-account results
      - `created_at` (timestamptz)

  3. Security
    - Enable RLS on `mass_update_log`
    - Add read/insert policies for anon and authenticated users

  4. Indexes
    - Index on `quote_lanes.lane_origin` for filtering
    - Index on `quotes.is_mass_update` for filtering
*/

-- 1. New columns on quote_lanes
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'quote_lanes' AND column_name = 'lane_status'
  ) THEN
    ALTER TABLE quote_lanes ADD COLUMN lane_status text DEFAULT 'New';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'quote_lanes' AND column_name = 'lane_origin'
  ) THEN
    ALTER TABLE quote_lanes ADD COLUMN lane_origin text DEFAULT 'Customer Request';
  END IF;
END $$;

-- 2. New column on accounts
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'accounts' AND column_name = 'customer_email'
  ) THEN
    ALTER TABLE accounts ADD COLUMN customer_email text DEFAULT '';
  END IF;
END $$;

-- 3. New columns on quotes
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'quotes' AND column_name = 'is_mass_update'
  ) THEN
    ALTER TABLE quotes ADD COLUMN is_mass_update boolean DEFAULT false;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'quotes' AND column_name = 'mass_update_log_id'
  ) THEN
    ALTER TABLE quotes ADD COLUMN mass_update_log_id uuid;
  END IF;
END $$;

-- 4. New table: mass_update_log
CREATE TABLE IF NOT EXISTS mass_update_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  run_at timestamptz NOT NULL DEFAULT now(),
  run_by text NOT NULL DEFAULT '',
  filter_criteria jsonb NOT NULL DEFAULT '{}',
  fields_modified jsonb NOT NULL DEFAULT '[]',
  total_lanes_selected integer NOT NULL DEFAULT 0,
  total_quotes_created integer NOT NULL DEFAULT 0,
  total_emails_sent integer NOT NULL DEFAULT 0,
  total_emails_flagged integer NOT NULL DEFAULT 0,
  results jsonb NOT NULL DEFAULT '[]',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE mass_update_log ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE policyname = 'Anon and auth can read mass_update_log'
  ) THEN
    CREATE POLICY "Anon and auth can read mass_update_log"
      ON mass_update_log FOR SELECT TO anon, authenticated USING (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE policyname = 'Anon and auth can insert mass_update_log'
  ) THEN
    CREATE POLICY "Anon and auth can insert mass_update_log"
      ON mass_update_log FOR INSERT TO anon, authenticated WITH CHECK (true);
  END IF;
END $$;

-- 5. Indexes
CREATE INDEX IF NOT EXISTS idx_quote_lanes_lane_origin ON quote_lanes(lane_origin);
CREATE INDEX IF NOT EXISTS idx_quotes_is_mass_update ON quotes(is_mass_update);
