/*
  # Session Settings (per profile) and Password Policies (org-wide)

  Salesforce-style security settings for the Smart Pricing Hub.

  ## profiles
  - session_timeout_minutes: inactivity timeout per profile (15/30/60/120/240). Default 120.
    Editable on system profiles too, so a dedicated RPC `set_profile_session_timeout` is
    provided (the existing `profiles_update_admin` policy blocks is_system = true rows).

  ## New tables
  - password_policies  : single row (id = 1), org-wide. Readable by any aal2 user (the client
                         validates against it), writable by admins only.
  - user_security      : per-user state (password_changed_at, must_change_password, failed
                         attempts, lockout). NO direct client access; RPCs / service role only.
  - password_history   : bcrypt hashes of previous passwords (generated by our Edge Function,
                         Supabase never exposes its own hashes). NO direct client access.
  - user_sessions      : one row per app session; last_activity_at drives server-side timeout
                         enforcement. NO direct client access.

  ## RPCs (SECURITY DEFINER)
  - start_session()                       -> creates a session row, returns its id
  - touch_session(p_session_id)           -> refreshes last_activity_at; expires the session if
                                             inactivity exceeded the profile timeout
  - end_session(p_session_id, p_reason)   -> closes the session
  - is_session_valid(p_session_id)        -> boolean, for write RPCs to reject expired sessions
  - set_profile_session_timeout(id, mins) -> admin only
  - admin_unlock_user(user_id)            -> admin only
  - admin_force_password_change(user_id)  -> admin only
  - admin_end_user_sessions(user_id)      -> admin only

  ## Permission key
  - admin.password_policies granted to the Full Access system profile.

  No existing policy, table, function or trigger is dropped or modified.
*/

-- ============================================================
-- 1. profiles.session_timeout_minutes
-- ============================================================
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                 WHERE table_schema='public' AND table_name='profiles' AND column_name='session_timeout_minutes') THEN
    ALTER TABLE public.profiles
      ADD COLUMN session_timeout_minutes integer NOT NULL DEFAULT 120
      CHECK (session_timeout_minutes IN (15, 30, 60, 120, 240));
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.set_profile_session_timeout(p_profile_id uuid, p_minutes integer)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Not authorized'; END IF;
  IF (SELECT auth.jwt()->>'aal') IS DISTINCT FROM 'aal2' THEN RAISE EXCEPTION 'MFA required'; END IF;
  IF p_minutes NOT IN (15, 30, 60, 120, 240) THEN RAISE EXCEPTION 'Invalid session timeout'; END IF;
  UPDATE public.profiles SET session_timeout_minutes = p_minutes WHERE id = p_profile_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Profile not found'; END IF;
END; $$;
REVOKE ALL ON FUNCTION public.set_profile_session_timeout(uuid, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_profile_session_timeout(uuid, integer) TO authenticated;

-- ============================================================
-- 2. password_policies (org-wide, single row)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.password_policies (
  id                 integer PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  expiration_days    integer CHECK (expiration_days IS NULL OR expiration_days IN (30, 60, 90, 180, 365)),
  history_count      integer NOT NULL DEFAULT 3 CHECK (history_count BETWEEN 0 AND 24),
  min_length         integer NOT NULL DEFAULT 8 CHECK (min_length IN (8, 10, 12, 15)),
  complexity         text    NOT NULL DEFAULT 'alpha_numeric'
    CHECK (complexity IN ('none','alpha_numeric','alpha_numeric_special','upper_lower_numeric','upper_lower_numeric_special')),
  max_login_attempts integer CHECK (max_login_attempts IS NULL OR max_login_attempts IN (3, 5, 10)),
  lockout_minutes    integer CHECK (lockout_minutes IS NULL OR lockout_minutes IN (15, 30, 60)),
  disallow_username  boolean NOT NULL DEFAULT true,
  updated_at         timestamptz NOT NULL DEFAULT now(),
  updated_by         uuid REFERENCES auth.users(id) ON DELETE SET NULL
);

INSERT INTO public.password_policies (id, expiration_days, max_login_attempts, lockout_minutes)
VALUES (1, 90, 10, 15)
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.password_policies ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "password_policies_select" ON public.password_policies;
DROP POLICY IF EXISTS "password_policies_update_admin" ON public.password_policies;
CREATE POLICY "password_policies_select" ON public.password_policies FOR SELECT TO authenticated
  USING ((SELECT auth.jwt()->>'aal') = 'aal2');
CREATE POLICY "password_policies_update_admin" ON public.password_policies FOR UPDATE TO authenticated
  USING ((SELECT auth.jwt()->>'aal') = 'aal2' AND public.is_admin())
  WITH CHECK ((SELECT auth.jwt()->>'aal') = 'aal2' AND public.is_admin());
-- No INSERT / DELETE policies on purpose: the single row is seeded here and never removed.

CREATE OR REPLACE FUNCTION public.trg_password_policies_touch()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  NEW.updated_at := now();
  NEW.updated_by := auth.uid();
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS password_policies_touch ON public.password_policies;
CREATE TRIGGER password_policies_touch BEFORE UPDATE ON public.password_policies
  FOR EACH ROW EXECUTE FUNCTION public.trg_password_policies_touch();

-- Permission key for the Setup page (Full Access system profile)
INSERT INTO public.profile_permissions (profile_id, permission_key, can_view, can_create, can_edit, can_delete)
VALUES ('b0000000-0000-0000-0000-000000000001', 'admin.password_policies', true, true, true, true)
ON CONFLICT (profile_id, permission_key) DO NOTHING;

-- ============================================================
-- 3. user_security
-- ============================================================
CREATE TABLE IF NOT EXISTS public.user_security (
  user_id               uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  password_changed_at   timestamptz NOT NULL DEFAULT now(),
  must_change_password  boolean NOT NULL DEFAULT false,
  failed_login_attempts integer NOT NULL DEFAULT 0,
  locked_until          timestamptz,
  locked_forever        boolean NOT NULL DEFAULT false,
  last_login_at         timestamptz,
  updated_at            timestamptz NOT NULL DEFAULT now()
);

-- Backfill: every existing auth user gets a row (password treated as changed "now")
INSERT INTO public.user_security (user_id)
SELECT u.id FROM auth.users u
ON CONFLICT (user_id) DO NOTHING;

ALTER TABLE public.user_security ENABLE ROW LEVEL SECURITY;
-- No policies: clients cannot read or write this table directly. Only SECURITY DEFINER
-- functions and the service role (Edge Functions) can.

-- Keep user_security in sync with new auth users
CREATE OR REPLACE FUNCTION public.trg_user_security_on_auth_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.user_security (user_id) VALUES (NEW.id) ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS user_security_on_auth_user ON auth.users;
CREATE TRIGGER user_security_on_auth_user AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.trg_user_security_on_auth_user();

-- ============================================================
-- 4. password_history
-- ============================================================
CREATE TABLE IF NOT EXISTS public.password_history (
  id            bigserial PRIMARY KEY,
  user_id       uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  password_hash text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS password_history_user_created_idx
  ON public.password_history (user_id, created_at DESC);

ALTER TABLE public.password_history ENABLE ROW LEVEL SECURITY;
-- No policies: service role only.

-- ============================================================
-- 5. user_sessions
-- ============================================================
CREATE TABLE IF NOT EXISTS public.user_sessions (
  session_id       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  started_at       timestamptz NOT NULL DEFAULT now(),
  last_activity_at timestamptz NOT NULL DEFAULT now(),
  ended_at         timestamptz,
  end_reason       text CHECK (end_reason IS NULL OR end_reason IN ('logout','timeout','admin'))
);
CREATE INDEX IF NOT EXISTS user_sessions_active_idx
  ON public.user_sessions (user_id) WHERE ended_at IS NULL;

ALTER TABLE public.user_sessions ENABLE ROW LEVEL SECURITY;
-- No policies: accessed only through the RPCs below.

-- Timeout (minutes) that applies to the current user, from their profile. Falls back to 120.
CREATE OR REPLACE FUNCTION public.current_session_timeout_minutes()
RETURNS integer
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT COALESCE((
    SELECT pr.session_timeout_minutes
    FROM public.user_profiles up
    JOIN public.profiles pr ON pr.id = up.profile_id
    WHERE up.id = auth.uid()
  ), 120);
$$;
REVOKE ALL ON FUNCTION public.current_session_timeout_minutes() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.current_session_timeout_minutes() TO authenticated;

-- start_session: creates a session row for the current user and returns its id
CREATE OR REPLACE FUNCTION public.start_session()
RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_id uuid;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  INSERT INTO public.user_sessions (user_id) VALUES (auth.uid()) RETURNING session_id INTO v_id;
  RETURN v_id;
END; $$;
REVOKE ALL ON FUNCTION public.start_session() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.start_session() TO authenticated;

-- touch_session: refresh activity. If inactivity already exceeded the timeout, close the
-- session with reason 'timeout' and report valid = false.
CREATE OR REPLACE FUNCTION public.touch_session(p_session_id uuid)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_row     public.user_sessions%ROWTYPE;
  v_timeout integer := public.current_session_timeout_minutes();
BEGIN
  SELECT * INTO v_row FROM public.user_sessions
  WHERE session_id = p_session_id AND user_id = auth.uid();

  IF NOT FOUND OR v_row.ended_at IS NOT NULL THEN
    RETURN jsonb_build_object('valid', false, 'timeout_minutes', v_timeout);
  END IF;

  IF v_row.last_activity_at < now() - make_interval(mins => v_timeout) THEN
    UPDATE public.user_sessions SET ended_at = now(), end_reason = 'timeout'
    WHERE session_id = p_session_id;
    RETURN jsonb_build_object('valid', false, 'timeout_minutes', v_timeout);
  END IF;

  UPDATE public.user_sessions SET last_activity_at = now() WHERE session_id = p_session_id;
  RETURN jsonb_build_object(
    'valid', true,
    'timeout_minutes', v_timeout,
    'expires_at', now() + make_interval(mins => v_timeout)
  );
END; $$;
REVOKE ALL ON FUNCTION public.touch_session(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.touch_session(uuid) TO authenticated;

-- end_session: explicit close (logout or client-side timeout)
CREATE OR REPLACE FUNCTION public.end_session(p_session_id uuid, p_reason text DEFAULT 'logout')
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF p_reason NOT IN ('logout','timeout') THEN RAISE EXCEPTION 'Invalid end reason'; END IF;
  UPDATE public.user_sessions SET ended_at = now(), end_reason = p_reason
  WHERE session_id = p_session_id AND user_id = auth.uid() AND ended_at IS NULL;
END; $$;
REVOKE ALL ON FUNCTION public.end_session(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.end_session(uuid, text) TO authenticated;

-- is_session_valid: used by write RPCs (later steps) to reject work from an expired session
CREATE OR REPLACE FUNCTION public.is_session_valid(p_session_id uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_sessions s
    WHERE s.session_id = p_session_id
      AND s.user_id = auth.uid()
      AND s.ended_at IS NULL
      AND s.last_activity_at >= now() - make_interval(mins => public.current_session_timeout_minutes())
  );
$$;
REVOKE ALL ON FUNCTION public.is_session_valid(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_session_valid(uuid) TO authenticated;

-- ============================================================
-- 6. Admin RPCs (User Management actions)
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_unlock_user(p_user_id uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Not authorized'; END IF;
  IF (SELECT auth.jwt()->>'aal') IS DISTINCT FROM 'aal2' THEN RAISE EXCEPTION 'MFA required'; END IF;
  INSERT INTO public.user_security (user_id) VALUES (p_user_id) ON CONFLICT (user_id) DO NOTHING;
  UPDATE public.user_security
  SET failed_login_attempts = 0, locked_until = NULL, locked_forever = false, updated_at = now()
  WHERE user_id = p_user_id;
END; $$;
REVOKE ALL ON FUNCTION public.admin_unlock_user(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_unlock_user(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_force_password_change(p_user_id uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Not authorized'; END IF;
  IF (SELECT auth.jwt()->>'aal') IS DISTINCT FROM 'aal2' THEN RAISE EXCEPTION 'MFA required'; END IF;
  INSERT INTO public.user_security (user_id) VALUES (p_user_id) ON CONFLICT (user_id) DO NOTHING;
  UPDATE public.user_security SET must_change_password = true, updated_at = now()
  WHERE user_id = p_user_id;
END; $$;
REVOKE ALL ON FUNCTION public.admin_force_password_change(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_force_password_change(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_end_user_sessions(p_user_id uuid)
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE v_count integer;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Not authorized'; END IF;
  IF (SELECT auth.jwt()->>'aal') IS DISTINCT FROM 'aal2' THEN RAISE EXCEPTION 'MFA required'; END IF;
  UPDATE public.user_sessions SET ended_at = now(), end_reason = 'admin'
  WHERE user_id = p_user_id AND ended_at IS NULL;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END; $$;
REVOKE ALL ON FUNCTION public.admin_end_user_sessions(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_end_user_sessions(uuid) TO authenticated;

-- Read-only security status for the Users tab (admins only)
CREATE OR REPLACE FUNCTION public.admin_get_user_security(p_user_id uuid)
RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT CASE WHEN public.is_admin() AND (SELECT auth.jwt()->>'aal') = 'aal2' THEN
    (SELECT jsonb_build_object(
       'password_changed_at',   s.password_changed_at,
       'must_change_password',  s.must_change_password,
       'failed_login_attempts', s.failed_login_attempts,
       'locked_until',          s.locked_until,
       'locked_forever',        s.locked_forever,
       'last_login_at',         s.last_login_at,
       'active_sessions',       (SELECT COUNT(*) FROM public.user_sessions x
                                 WHERE x.user_id = s.user_id AND x.ended_at IS NULL)
     ) FROM public.user_security s WHERE s.user_id = p_user_id)
  ELSE NULL END;
$$;
REVOKE ALL ON FUNCTION public.admin_get_user_security(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_get_user_security(uuid) TO authenticated;